// Generated by CoffeeScript 1.7.1
(function() {
  var Redis;

  Redis = require('../database/redis');

  module.exports = function() {
    var routes;
    routes = ['/api/menu/get'];
    return function(req, res, next) {
      var id, path;
      path = req._parsedUrl.pathname;
      id = req.method === 'GET' ? req.query.id : req.body.id;
      if (routes.indexOf(path) !== -1) {
        if (id) {
          return Redis.getUser(id, function(err, result) {
            if (result) {
              return next();
            } else if (err) {
              return res.json({
                status: false,
                result: '出错啦，请稍后再试',
                need_login: true
              });
            } else {
              return res.json({
                status: false,
                result: '请登录后再试',
                need_login: true
              });
            }
          });
        } else {
          return res.json({
            status: false,
            result: '请登录后再试',
            need_login: true
          });
        }
      } else {
        if (id) {
          Redis.getUser(id);
        }
        return next();
      }
    };
  };

}).call(this);

//# sourceMappingURL=api_auth.map
