// Generated by CoffeeScript 1.7.1
(function() {
  var log4js;

  log4js = require('log4js');

  exports.logger = function(options) {
    return log4js.connectLogger(log4js.getLogger("request"), options);
  };

}).call(this);

//# sourceMappingURL=log.map
