// Generated by CoffeeScript 1.7.1
(function() {
  var auth, sms;

  auth = require('../lib/auth');

  sms = require('../lib/sms');

  module.exports = function(app) {
    app.get('/console', auth.isAuthenticated(), function(req, res) {
      return res.render('console');
    });
    return app.get('/sms/left', auth.isAuthenticated(), function(req, res) {
      return sms.left(res);
    });
  };

}).call(this);

//# sourceMappingURL=console.map
