// Generated by CoffeeScript 1.7.1
(function() {
  var auth, passport;

  auth = require('../lib/auth');

  passport = require('passport');

  module.exports = function(app) {
    app.get('/', function(req, res) {
      var error, model;
      error = req.flash('error');
      model = {};
      if (error) {
        model.message = error[0];
      }
      return res.render('index', model);
    });
    app.get('/setting', function(req, res) {
      return res.render('setting');
    });
    return app.post('/login', function(req, res) {
      var data;
      data = req.body;
      if (data.action === 'apply') {
        return res.direct('/apply');
      }
      if (!data.username || !data.password) {
        return res.render('index', {
          message: '用户名或密码不能为空'
        });
      }
      return passport.authenticate('local', {
        successRedirect: req.session.goingTo || '/console',
        failureRedirect: '/',
        failureFlash: true
      })(req, res);
    });
  };

}).call(this);

//# sourceMappingURL=index.map
