// Generated by CoffeeScript 1.7.1
(function() {
  var Log, auth, models;

  models = require('../models');

  Log = models.Log;

  auth = require('../lib/auth');

  module.exports = function(app) {
    return app.get('/logs', auth.isAuthenticated(), function(req, res) {});
  };

}).call(this);

//# sourceMappingURL=log.map
