// Generated by CoffeeScript 1.7.1
(function() {
  var Song, auth;

  auth = require('../lib/auth');

  Song = require('../models').Song;

  module.exports = function(app) {
    app.get('/songs', auth.isAuthenticated(), function(req, res) {
      return res.render('songs');
    });
    app.get('/song/list', auth.isAuthenticated(), function(req, res) {
      var andArr, arr, data, query;
      data = req.query;
      query = {};
      if (data.name) {
        query = {
          'name': new RegExp(data.name, 'i')
        };
      }
      if (data.tags) {
        arr = tags.split(',');
        andArr = [];
        arr.forEach(function(tag) {
          return andArr.push({
            tags: tag
          });
        });
        query.$and = andArr;
      }
      return Song.find(query).populate('creator', 'username').populate('updator', 'username').sort({
        'created_at': -1
      }).limit(data.perPage).skip(data.perPage * (data.page - 1)).exec(function(err, result) {
        if (err) {
          return Error(err, res);
        } else {
          return res.json({
            status: true,
            results: result
          });
        }
      });
    });
    return app.post('/song/update', auth.isAuthenticated(), function(req, res) {
      var data;
      data = req.body;
      data.updator = req.user._id;
      return Song.findById(data._id, function(err, result) {
        if (err) {
          return Error(err, res);
        } else {
          UpdateObject(result, data);
          return result.save(function(err, result) {
            if (err) {
              return Error(err, res);
            } else {
              return res.json({
                status: true,
                results: result
              });
            }
          });
        }
      });
    });
  };

}).call(this);

//# sourceMappingURL=songs.map
