// Generated by CoffeeScript 1.7.1
(function() {
  var LocalStrategy, Manager, log4js, logger;

  Manager = require('../models').Manager;

  LocalStrategy = require('passport-local').Strategy;

  log4js = require('log4js');

  logger = log4js.getLogger('Auth');

  exports.config = function(settings) {};

  exports.localStrategy = function() {
    return new LocalStrategy(function(username, password, done) {
      return Manager.getAuthenticated(username, password, function(err, user, reason) {
        if (err) {
          logger.error(err);
        }
        if (!user) {
          logger.warn('Login Failed:' + username + '-' + password + '-' + reason);
          return done(err, false, {
            message: reason
          });
        } else {
          logger.trace('Loged in:' + username);
        }
        return done(null, user);
      });
    });
  };

  exports.isAuthenticated = function(role) {
    return function(req, res, next) {
      if (!req.isAuthenticated()) {
        req.session.goingTo = req.url;
        return res.redirect('/');
      } else {
        if (role && req.user.role !== role) {
          res.status(401);
          res.render('errors/401');
        }
        return next();
      }
    };
  };

  exports.injectUser = function(req, res, next) {
    var navs, user;
    if (req.isAuthenticated()) {
      user = req.user;
      res.locals.user = user;
      res.locals.path = req.path;
      navs = [
        {
          href: '/console',
          label: '控制台'
        }, {
          href: '/songs',
          label: '媒资管理'
        }, {
          href: '/menu',
          label: '歌单推送'
        }, {
          href: '/dm',
          label: 'DM管理'
        }, {
          href: '/dm_menu',
          label: 'DM推送'
        }, {
          href: '/clients',
          label: '客户管理'
        }, {
          href: '/feedback',
          label: '客户反馈'
        }, {
          href: '/log',
          label: '操作日志'
        }
      ];
      if (user.role === 0) {
        navs.push({
          href: '/setting',
          label: '系统设置'
        });
      }
      res.locals.navs = JSON.stringify(navs);
    }
    return next();
  };

}).call(this);

//# sourceMappingURL=auth.map
