// Generated by CoffeeScript 1.7.1
(function() {
  var ModalInstanceCtrl, client;

  client = angular.module('UserMApp', ['ngGrid', 'ui.bootstrap', 'ngTagsInput']);

  client.controller('UserMCtrl', function($scope, $http, $modal, $q, $filter) {
    var listUri, updateStatus, updateStatusUri;
    listUri = '/user/list';
    updateStatusUri = '/user/update/status';
    configScopeForNgGrid($scope);
    $scope.search = function() {
      $scope.page = 1;
      $scope.list = null;
      return $scope.getList();
    };
    $scope.getList = function() {
      var tags;
      tags = '';
      if ($scope.s_tags) {
        tags = [];
        $scope.s_tags.forEach(function(tag) {
          return tags.push(tag.text);
        });
        tags = tags.join(',');
      }
      return $http.get(listUri, {
        params: {
          username: $scope.searchText,
          tags: tags,
          page: $scope.page,
          perPage: 20
        }
      }).success(function(result) {
        if (result.status) {
          if (!$scope.list) {
            return $scope.list = result.results;
          } else if (result.results && result.results.length) {
            return result.results.forEach(function(item) {
              return $scope.list.push(item);
            });
          } else {
            return showAlert('没有更多的数据了');
          }
        } else {
          return showAlert(result.error);
        }
      });
    };
    $scope.getList();
    $scope.tags = [];
    getDict($http, 'ClientTags', function(result) {
      if (result && result.list && result.list.length) {
        return result.list.forEach(function(tag) {
          console.log(tag);
          if (typeof tag === 'string') {
            return $scope.tags.push({
              text: tag
            });
          } else {
            return $scope.tags.push(tag);
          }
        });
      }
    });
    $scope.loadTags = function(query) {
      var deffered;
      deffered = $q.defer();
      deffered.resolve($filter('filter')($scope.tags, query));
      return deffered.promise;
    };
    $scope.updateStatus = function(data) {
      if (!data.disabled) {
        return confirm(2, '客户状态更新', '是否确认禁用该客户，一旦禁用后该客户将不能使用软件', function(value) {
          if (value) {
            return updateStatus(data);
          }
        });
      } else {
        return updateStatus(data);
      }
    };
    updateStatus = function(data) {
      $scope.updating = true;
      data.disabled = !data.disabled;
      return $http.post(updateStatusUri, {
        _id: data._id,
        disabled: data.disabled
      }).success(function(result) {
        if (!result.status) {
          showAlert(result.error);
        }
        return $scope.updating = false;
      });
    };
    $scope.page = 1;
    $scope.$on('ngGridEventScroll', function() {
      $scope.page++;
      return $scope.getList();
    });
    $scope.dataGrid = {
      data: 'list',
      multiSelect: false,
      enableRowSelection: false,
      enableSorting: false,
      enableHighlighting: true,
      rowHeight: 40,
      columnDefs: [
        {
          field: "username",
          displayName: "客户名称",
          cellTemplate: textCellTemplate
        }, {
          field: "code",
          displayName: "客户密码",
          cellTemplate: textCellTemplate
        }, {
          field: "parent.username",
          displayName: "总部",
          cellTemplate: textCellTemplate
        }, {
          field: "tags",
          displayName: "标签",
          cellTemplate: textCellTemplate
        }, {
          field: "man",
          displayName: "联系人",
          cellTemplate: textCellTemplate
        }, {
          field: "mobile",
          displayName: "手机号",
          width: 115,
          cellTemplate: textCellTemplate
        }, {
          field: "email",
          displayName: "邮箱",
          cellTemplate: textCellTemplate
        }, {
          field: "creator.username",
          width: 88,
          displayName: "创建者",
          cellTemplate: textCellTemplate
        }, {
          field: "created_at",
          width: 100,
          displayName: "创建时间",
          cellTemplate: dateCellTemplate
        }, {
          field: "handler",
          displayName: "操作",
          width: 100,
          cellTemplate: '<div class="row" ng-style="{height: rowHeight}"> <div class="col-md-12 text-center" style="padding: 0px; display: inline-block; vertical-align: middle; margin-top: 8px"> <a class="btn btn-primary btn-xs " ng-click="edit(row.entity)">编辑</a> <a class="btn btn-xs" ng-class="getButtonStyle(row.getProperty(\'disabled\'))" ng-click="updateStatus(row.entity)" ng-disabled="updating">{{ isDisabled(row.getProperty("disabled")) }}</a></div></div>'
        }
      ]
    };
    $scope.edit = function(data) {
      $scope.data = data;
      return $scope.open();
    };
    $scope.add = function() {
      $scope.data = {};
      $scope.open();
    };
    $scope.open = function() {
      var modalInstance;
      modalInstance = $modal.open({
        templateUrl: 'modal.html',
        controller: ModalInstanceCtrl,
        backdrop: 'static',
        resolve: {
          data: function() {
            return $scope.data;
          },
          http: function() {
            return $http;
          },
          tags: function() {
            return $scope.tags;
          }
        }
      });
      modalInstance.result.then((function(data) {
        if (!$scope.list) {
          $scope.list = [];
        }
        if (data === 'refresh') {
          $scope.list = null;
          $scope.page = 1;
          $scope.getList();
        } else if (data) {
          $scope.list.unshift(data);
        }
      }), function() {});
    };
  });

  angular.bootstrap(document.getElementById("userMDiv"), ['UserMApp']);

  ModalInstanceCtrl = function($scope, $timeout, $modalInstance, data, http, tags, $q, $filter) {
    var getParents;
    $scope.data = data;
    $scope.buttonDisabled = false;
    $scope.tags = tags;
    getParents = function() {
      return http.get('/user/parents').success(function(result) {
        return $scope.parents = result.result;
      });
    };
    getParents();
    if (data._id) {
      $scope.update = true;
      $scope.title = '编辑客户';
    } else {
      $scope.title = '新增客户';
    }
    $scope.loadTags = function(query) {
      var deffered;
      deffered = $q.defer();
      deffered.resolve($filter('filter')($scope.tags, query));
      return deffered.promise;
    };
    $scope.cancel = function() {
      $modalInstance.close();
    };
    $scope.select = function(value) {
      $scope.selectedType = value;
    };
    $scope.ok = function() {
      var msg;
      data = angular.copy($scope.data);
      if (!data.username) {
        msg = '客户名称必填';
      }
      if (msg) {
        $scope.msg = msg;
        return;
      } else {
        tags = [];
        if (data.tags) {
          data.tags.forEach(function(tag) {
            if (typeof tag === 'string') {
              return tags.push(tag);
            } else {
              return tags.push(tag.text);
            }
          });
        }
        data.tags = tags;
        $scope.buttonDisabled = true;
        if ($scope.update) {
          delete data['parent'];
          http.post('/user/update', data).success(function(result) {
            if (result.status) {
              return $modalInstance.close('refresh');
            } else {
              $scope.msg = result.results;
              return $scope.buttonDisabled = false;
            }
          }).error(function(error) {
            $scope.msg = '出错了，请稍后再试';
            return $scope.buttonDisabled = false;
          });
        } else {
          http.post('/user/add', data).success(function(result) {
            if (result.status) {
              return $modalInstance.close(result.results);
            } else {
              $scope.msg = result.results;
              return $scope.buttonDisabled = false;
            }
          }).error(function(error) {
            $scope.msg = '出错了，请稍后再试';
            return $scope.buttonDisabled = false;
          });
        }
      }
    };
  };

}).call(this);

//# sourceMappingURL=client.map
