// Generated by CoffeeScript 1.7.1
(function() {
  var ErrorLogSchema, Mongoose, Schema;

  Mongoose = require('mongoose');

  Schema = Mongoose.Schema;

  ErrorLogSchema = new Schema({
    client: {
      type: Schema.Types.ObjectId,
      ref: 'Client'
    },
    url: String,
    created_at: String
  });

  ErrorLogSchema.index({
    client: 1,
    created_at: -1
  });

  Mongoose.model('ErrorLog', ErrorLogSchema);

}).call(this);

//# sourceMappingURL=error_log.map
