// Generated by CoffeeScript 1.7.1
(function() {
  var Mongoose;

  Mongoose = require('mongoose');

  require('./sms');

  require('./manager');

  module.exports = {
    SMS: Mongoose.model("SMS"),
    Manager: Mongoose.model("Manager")
  };

}).call(this);

//# sourceMappingURL=index.map
