// Generated by CoffeeScript 1.7.1
(function() {
  var Mongoose;

  Mongoose = require('mongoose');

  require('./sms');

  require('./manager');

  require('./dict');

  require('./client');

  require('./song');

  require('./menu');

  require('./dm');

  module.exports = {
    SMS: Mongoose.model("SMS"),
    Manager: Mongoose.model("Manager"),
    Dict: Mongoose.model('Dict'),
    Client: Mongoose.model('Client'),
    Song: Mongoose.model('Song'),
    Menu: Mongoose.model('Menu'),
    DM: Mongoose.model('DM'),
    updateTags: function(key, tags) {
      var Dict;
      if (tags) {
        Dict = module.exports.Dict;
        return Dict.findOne({
          key: key
        }, function(err, dic) {
          if (dic) {
            if (dic.list) {
              tags.forEach(function(tag) {
                if (dic.list.indexOf(tag) === -1) {
                  return dic.list.addToSet(tag);
                }
              });
            } else {
              dic.list = tags;
            }
          } else {
            dic = new Dict({
              key: key,
              list: tags
            });
          }
          return dic.save();
        });
      }
    }
  };

}).call(this);

//# sourceMappingURL=index.map
