// Generated by CoffeeScript 1.7.1
(function() {
  var ClientsModalInstanceCtrl, ModalInstanceCtrl, menu;

  menu = angular.module('MenuApp', ['ngGrid', 'ngRoute', 'ngTagsInput', 'ui.bootstrap']);

  menu.controller('MenuCtrl', function($scope, $http, $modal, $q, $filter) {
    var listUri, updateStatus, updateStatusUri, validateTime;
    $scope.module = 'templates/html/menu/home.html';
    listUri = '/menu/list';
    updateStatusUri = '/menu/update/status';
    configScopeForNgGrid($scope);
    configDateForScope($scope);
    $scope.search = function() {
      $scope.page = 1;
      $scope.list = null;
      return $scope.getList();
    };
    $scope.getList = function() {
      var tags;
      tags = '';
      if ($scope.s_tags) {
        tags = [];
        $scope.s_tags.forEach(function(tag) {
          return tags.push(tag.text);
        });
        tags = tags.join(',');
      }
      return $http.get(listUri, {
        params: {
          type: 2,
          name: $scope.menuName,
          tags: tags,
          page: $scope.page,
          perPage: 20
        }
      }).success(function(result) {
        if (result.status) {
          if (!$scope.list) {
            return $scope.list = result.results;
          } else if (result.results && result.results.length) {
            return result.results.forEach(function(item) {
              return $scope.list.push(item);
            });
          } else {
            return showAlert('没有更多的数据了');
          }
        } else {
          return showAlert(result.error);
        }
      });
    };
    $scope.getList();
    $scope.updateStatus = function(data) {
      if (!data.disabled) {
        return confirm(2, 'DM列表状态更新', '是否确认禁用该DM列表，一旦禁用后客户将不能再不会再使用DM列表', function(value) {
          if (value) {
            return updateStatus(data);
          }
        });
      } else {
        return updateStatus(data);
      }
    };
    updateStatus = function(data) {
      $scope.updating = true;
      data.disabled = !data.disabled;
      return $http.post(updateStatusUri, {
        _id: data._id,
        disabled: data.disabled
      }).success(function(result) {
        if (!result.status) {
          showAlert(result.error);
        }
        return $scope.updating = false;
      });
    };
    $scope.page = 1;
    $scope.$on('ngGridEventScroll', function() {
      $scope.page++;
      return $scope.getList();
    });
    $scope.dataGrid = {
      data: 'list',
      multiSelect: false,
      enableRowSelection: false,
      enableSorting: false,
      enableHighlighting: true,
      rowHeight: 40,
      columnDefs: [
        {
          field: "name",
          displayName: "名称",
          cellTemplate: textCellTemplate
        }, {
          field: "tags",
          displayName: "标签",
          cellTemplate: textCellTemplate
        }, {
          field: "clients.length",
          displayName: "使用客户",
          cellTemplate: textCellTemplate
        }, {
          field: "begin_date",
          displayName: "开始日期",
          cellTemplate: dateCellTemplate
        }, {
          field: "end_date",
          displayName: "结束日期",
          cellTemplate: dateCellTemplate
        }, {
          field: "creator.username",
          width: 88,
          displayName: "创建者",
          cellTemplate: textCellTemplate
        }, {
          field: "created_at",
          width: 100,
          displayName: "创建时间",
          cellTemplate: dateCellTemplate
        }, {
          field: "handler",
          displayName: "操作",
          width: 150,
          cellTemplate: '<div class="row" ng-style="{height: rowHeight}"> <div class="col-md-12 text-center" style="padding: 0px; display: inline-block; vertical-align: middle; margin-top: 8px"> <a class="btn btn-info btn-xs" ng-click="clients(row.entity)">客户</a> <a class="btn btn-primary btn-xs" ng-click="edit(row.entity)">编辑</a> <a class="btn btn-xs" ng-class="getButtonStyle(row.getProperty(\'disabled\'))" ng-click="updateStatus(row.entity)" ng-disabled="updating">{{ isDisabled(row.getProperty("disabled")) }}</a></div></div>'
        }
      ]
    };
    $scope.songGrid = {
      data: 'data.dm_list',
      multiSelect: false,
      enableRowSelection: false,
      enableSorting: false,
      enableHighlighting: false,
      enableCellEdit: true,
      columnDefs: [
        {
          field: "dm.name",
          displayName: "名称",
          cellTemplate: textCellTemplate
        }, {
          field: "playTime",
          displayName: "播放时间",
          cellTemplate: textCellTemplate
        }, {
          field: "dm.duration",
          displayName: "时长（秒）",
          cellTemplate: textCellTemplate
        }, {
          field: "repeat",
          displayName: "重复次数",
          cellTemplate: textCellTemplate
        }, {
          field: "interval",
          displayName: "间隔时间（秒）",
          cellTemplate: textCellTemplate
        }, {
          field: "handler",
          displayName: "操作",
          width: 100,
          cellTemplate: '<div class="row" ng-style="{height: rowHeight}"> <div class="col-md-12 text-center" style="padding: 0px; display: inline-block; vertical-align: middle; margin-top: 3px"> <a class="btn btn-warning btn-xs" ng-click="removeSong(row.entity)">移除</a> </div></div>'
        }
      ]
    };
    $scope.removeSong = function(song) {
      var arr;
      arr = $scope.dm_list;
      return arr.splice(arr.indexOf(song), 1);
    };
    $scope.edit = function(data) {
      $scope.data = data;
      return $scope.module = 'templates/html/menu/dm_edit.html';
    };
    $scope.add = function() {
      $scope.data = {
        dm_list: []
      };
      return $scope.module = 'templates/html/menu/dm_edit.html';
    };
    $scope.back = function() {
      $scope.module = 'templates/html/menu/home.html';
      $scope.list = null;
      return $scope.getList();
    };
    validateTime = function(time) {
      var arr, h, m, wrong;
      if (!time) {
        wrong = true;
      } else {
        wrong = false;
        if (time.indexOf(':') === -1) {
          wrong = true;
        } else {
          arr = time.split(':');
          if (arr.length !== 2) {
            wrong = true;
          } else {
            h = parseInt(arr[0]);
            m = parseInt(arr[1]);
            time = moment({
              hour: h,
              minute: m
            });
            if (!time.isValid()) {
              wrong = true;
            }
          }
        }
      }
      if (wrong) {
        return false;
      } else {
        return time;
      }
    };
    $scope.addSong = function() {
      return $scope.open();
    };
    $scope.tags = [];
    getDict($http, 'MenuTags', function(result) {
      if (result && result.list && result.list.length) {
        return result.list.forEach(function(tag) {
          if (typeof tag === 'string') {
            return $scope.tags.push({
              text: tag
            });
          } else {
            return $scope.tags.push(tag);
          }
        });
      }
    });
    $scope.loadTags = function(query) {
      var deffered;
      deffered = $q.defer();
      deffered.resolve($filter('filter')($scope.tags, query));
      return deffered.promise;
    };
    $scope.saveMenu = function() {
      var list, tags, temp_list, wrong;
      $scope.handling = false;
      menu = angular.copy($scope.data);
      if (!menu.name) {
        wrong = 'DM列表名称不能为空';
      }
      if (menu.quality) {
        if (parseInt(menu.quality) !== 64 && parseInt(menu.quality) !== 192) {
          wrong = '音频质量目前仅支持64和192两种';
        }
      }
      if (menu.dm_list) {
        menu.dm_list.forEach(function(dm) {
          var playTime;
          playTime = validateTime(dm.playTime);
          if (!playTime) {
            wrong = '播放时间格式不对，必须是10:10这样的格式，注意冒号';
            console.log(wrong);
            return false;
          }
        });
      }
      if (wrong) {
        return confirm(1, '保存失败', wrong);
      } else {
        list = menu.dm_list;
        temp_list = angular.copy(list);
        list.forEach(function(list) {
          return list.dm = list.dm._id;
        });
        tags = [];
        if (menu.tags) {
          menu.tags.forEach(function(tag) {
            if (typeof tag === 'string') {
              return tags.push(tag);
            } else {
              return tags.push(tag.text);
            }
          });
        }
        menu.tags = tags;
        menu.type = 2;
        if (!menu._id) {
          return $http.post('/menu/add', menu).success(function(result) {
            if (!result.status) {
              showAlert(result.error);
            }
            $scope.data = result.results;
            $scope.data.dm_list = temp_list;
            return confirm(2, '保存成功', '继续编辑或返回DM列表', function(value) {
              if (!value) {
                return $scope.back();
              }
            }, '继续编辑', '返回列表');
          });
        } else {
          return $http.post('/menu/update', menu).success(function(result) {
            if (!result.status) {
              showAlert(result.error);
            }
            return confirm(2, '保存成功', '继续编辑或返回DM列表', function(value) {
              if (!value) {
                return $scope.back();
              }
            }, '继续编辑', '返回列表');
          });
        }
      }
    };
    $scope.clients = function(menu) {
      var modalInstance;
      modalInstance = $modal.open({
        templateUrl: 'clients.html',
        controller: ClientsModalInstanceCtrl,
        backdrop: 'static',
        resolve: {
          menu: function() {
            return menu;
          }
        }
      });
      return modalInstance.result.then((function(clients) {
        if (clients) {
          return $http.post('/menu/update', {
            _id: menu._id,
            clients: clients
          }).success(function(result) {
            if (!result.status) {
              showAlert(result.error);
            }
            return $scope.search();
          });
        }
      }), function() {});
    };
    return $scope.open = function() {
      var modalInstance;
      modalInstance = $modal.open({
        templateUrl: 'modal.html',
        controller: ModalInstanceCtrl,
        backdrop: 'static',
        resolve: {
          songs: function() {
            var arr;
            arr = [];
            $scope.data.dm_list.forEach(function(s) {
              return arr.push(s.dm);
            });
            return arr;
          }
        }
      });
      return modalInstance.result.then((function(data) {
        var dm_menu;
        if (data) {
          dm_menu = $scope.data;
          if (!dm_menu.dm_list) {
            dm_menu.dm_list = [];
          }
          data.forEach(function(s) {
            var has;
            has = false;
            if (!has) {
              return dm_menu.dm_list.push({
                dm: s,
                repeat: 0,
                playTime: '00:00',
                interval: 0
              });
            }
          });
        }
      }), function() {});
    };
  });

  ClientsModalInstanceCtrl = function($scope, $http, $timeout, $modalInstance, $q, $filter, menu) {
    var choosed, choosedLabel, choosedStyle, listUri, refreshStatus;
    listUri = '/user/list';
    configScopeForNgGrid($scope);
    menu = angular.copy(menu);
    $scope.clients = menu.clients;
    $scope.search = function() {
      $scope.page = 1;
      $scope.list = null;
      return $scope.getList();
    };
    $scope.getList = function() {
      var tags;
      tags = '';
      if ($scope.s_tags) {
        tags = [];
        $scope.s_tags.forEach(function(tag) {
          return tags.push(tag.text);
        });
        tags = tags.join(',');
      }
      return $http.get(listUri, {
        params: {
          username: $scope.searchText,
          tags: tags,
          page: $scope.page,
          perPage: 20
        }
      }).success(function(result) {
        if (result.status) {
          if (!$scope.list) {
            $scope.list = result.results;
            return refreshStatus();
          } else if (result.results && result.results.length) {
            result.results.forEach(function(item) {
              return $scope.list.push(item);
            });
            return refreshStatus();
          } else {
            return showAlert('没有更多的数据了');
          }
        } else {
          return showAlert(result.error);
        }
      });
    };
    refreshStatus = function() {
      return $scope.list.forEach(function(item) {
        item.style = choosedStyle(item);
        return item.label = choosedLabel(item);
      });
    };
    $scope.getList();
    $scope.tags = [];
    getDict($http, 'ClientTags', function(result) {
      if (result && result.list && result.list.length) {
        return result.list.forEach(function(tag) {
          if (typeof tag === 'string') {
            return $scope.tags.push({
              text: tag
            });
          } else {
            return $scope.tags.push(tag);
          }
        });
      }
    });
    $scope.loadTags = function(query) {
      var deffered;
      deffered = $q.defer();
      deffered.resolve($filter('filter')($scope.tags, query));
      return deffered.promise;
    };
    $scope.page = 1;
    $scope.$on('ngGridEventScroll', function() {
      $scope.page++;
      return $scope.getList();
    });
    choosed = function(data) {
      var has;
      has = false;
      $scope.clients.forEach(function(c) {
        if (c === data._id) {
          return has = true;
        }
      });
      return has;
    };
    choosedStyle = function(data) {
      if (choosed(data)) {
        return 'btn-warning';
      } else {
        return 'btn-success';
      }
    };
    choosedLabel = function(data) {
      if (choosed(data)) {
        return '取消';
      } else {
        return '选中';
      }
    };
    $scope.handle = function(data) {
      var i;
      if (choosed(data)) {
        i = 0;
        while (i < $scope.clients.length) {
          if ($scope.clients[i] === data._id) {
            $scope.clients.splice(i, 1);
          }
          i++;
        }
      } else {
        if ($scope.clients.indexOf(data._id) === -1) {
          $scope.clients.push(data._id);
        }
      }
      return refreshStatus();
    };
    $scope.cancel = function() {
      $modalInstance.close();
    };
    $scope.ok = function() {
      $modalInstance.close($scope.clients);
    };
    return $scope.dataGrid = {
      data: 'list',
      multiSelect: false,
      enableRowSelection: false,
      enableSorting: false,
      enableHighlighting: true,
      rowHeight: 40,
      columnDefs: [
        {
          field: "username",
          displayName: "客户名称",
          cellTemplate: textCellTemplate
        }, {
          field: "parent.username",
          displayName: "总部",
          cellTemplate: textCellTemplate
        }, {
          field: "tags",
          displayName: "标签",
          cellTemplate: textCellTemplate
        }, {
          field: "handler",
          displayName: "操作",
          width: 100,
          cellTemplate: '<div class="row" ng-style="{height: rowHeight}"> <div class="col-md-12 text-center" style="padding: 0px; display: inline-block; vertical-align: middle; margin-top: 8px"> <a class="btn btn-xs" ng-class="row.entity.style" ng-click="handle(row.entity)" ng-disabled="updating">{{ row.entity.label }}</a></div></div>'
        }
      ]
    };
  };

  ModalInstanceCtrl = function($scope, $http, $timeout, $modalInstance, $q, $filter, songs) {
    var choosed, choosedLabel, choosedStyle, listUri, refreshStatus;
    listUri = '/dm/list';
    configScopeForNgGrid($scope);
    $scope.title = '插入DM，单个DM可选择多次';
    $scope.songs = angular.copy(songs);
    console.log($scope.songs);
    $scope.search = function() {
      $scope.page = 1;
      $scope.list = null;
      return $scope.getList();
    };
    $scope.getList = function() {
      var tags;
      tags = '';
      if ($scope.s_tags) {
        tags = [];
        $scope.s_tags.forEach(function(tag) {
          return tags.push(tag.text);
        });
        tags = tags.join(',');
      }
      return $http.get(listUri, {
        params: {
          name: $scope.searchText,
          tags: tags,
          page: $scope.page,
          perPage: 20
        }
      }).success(function(result) {
        if (result.status) {
          if (!$scope.list) {
            $scope.list = result.results;
            return refreshStatus();
          } else if (result.results && result.results.length) {
            result.results.forEach(function(item) {
              return $scope.list.push(item);
            });
            return refreshStatus();
          } else {
            return showAlert('没有更多的数据了');
          }
        } else {
          return showAlert(result.error);
        }
      });
    };
    $scope.getList();
    $scope.page = 1;
    $scope.$on('ngGridEventScroll', function() {
      $scope.page++;
      return $scope.getList();
    });
    refreshStatus = function() {
      return $scope.list.forEach(function(item) {
        item.style = choosedStyle(item);
        return item.label = choosedLabel(item);
      });
    };
    choosed = function(data) {
      var has;
      has = false;
      return has;
    };
    choosedStyle = function(data) {
      if (choosed(data)) {
        return 'btn-warning';
      } else {
        return 'btn-success';
      }
    };
    choosedLabel = function(data) {
      if (choosed(data)) {
        return '取消';
      } else {
        return '选中';
      }
    };
    $scope.handle = function(data) {
      return $scope.songs.push(data);
    };
    $scope.dataGrid = {
      data: 'list',
      multiSelect: false,
      enableRowSelection: false,
      enableSorting: false,
      enableHighlighting: true,
      rowHeight: 40,
      columnDefs: [
        {
          field: "name",
          displayName: "名称",
          cellTemplate: textCellTemplate
        }, {
          field: "handler",
          displayName: "操作",
          width: 100,
          cellTemplate: '<div class="col-md-12 text-center" style="padding: 0px; display: inline-block; vertical-align: middle; margin-top: 8px"> <a style="margin-top: 3px" class="btn btn-success btn-xs" ng-class="row.entity.style" ng-click="handle(row.entity)">{{ row.entity.label }}</a> </div></div>'
        }
      ]
    };
    $scope.tags = [];
    getDict($http, 'DMTags', function(result) {
      if (result && result.list && result.list.length) {
        return result.list.forEach(function(tag) {
          if (typeof tag === 'string') {
            return $scope.tags.push({
              text: tag
            });
          } else {
            return $scope.tags.push(tag);
          }
        });
      }
    });
    $scope.loadTags = function(query) {
      var deffered;
      deffered = $q.defer();
      deffered.resolve($filter('filter')($scope.tags, query));
      return deffered.promise;
    };
    $scope.cancel = function() {
      $modalInstance.close();
    };
    return $scope.ok = function() {
      $modalInstance.close($scope.songs);
    };
  };

  angular.element(document).ready(function() {
    return angular.bootstrap(document.getElementById("menuDiv"), ['MenuApp']);
  });

}).call(this);

//# sourceMappingURL=dm_menu.map
